from pathlib import Path

BASE = Path("knowledge_base")
BASE.mkdir(exist_ok=True)

files = {

"panels.txt": """
SOLAR PANELS

Definition:

A solar panel, also known as a photovoltaic (PV) panel, converts sunlight into electrical energy through the photovoltaic effect.

How Solar Panels Work:

1. Solar panels contain photovoltaic cells.
2. These cells commonly use semiconductor materials such as silicon.
3. Sunlight causes electrical charges to move within the cells.
4. The generated electricity is direct current (DC).
5. An inverter can convert DC electricity into alternating current (AC).

Common Types:

1. Monocrystalline
2. Polycrystalline
3. Thin-film

Monocrystalline Panels:

Monocrystalline panels are made using high-purity silicon and generally offer high efficiency.

Advantages:
- High efficiency
- Good power output per unit area
- Suitable for limited installation space
- Long operating life

Limitations:
- Usually higher initial cost
- Performance is affected by shading, temperature, orientation, and installation conditions

Polycrystalline Panels:

Polycrystalline panels are manufactured using multiple silicon crystal structures.

Advantages:
- Generally lower manufacturing cost
- Reliable technology
- Suitable for residential and commercial applications

Limitations:
- Generally lower efficiency than comparable modern monocrystalline panels
- May require more installation area

Thin-Film Panels:

Thin-film panels use thin layers of photovoltaic material deposited onto a supporting surface.

Advantages:
- Lightweight options are available
- Flexible designs may be possible
- Useful for specialized applications

Limitations:
- Generally lower efficiency
- May require more installation area

Important Specifications:

- Rated power output in watts (W)
- Efficiency
- Voltage
- Current
- Temperature coefficient
- Dimensions
- Weight
- Operating temperature range
- Warranty
- Certifications

Panel Wattage:

Solar panels are available in different power ratings. Higher wattage does not automatically mean better performance. Panel selection should consider efficiency, available space, system design, quality, warranty, and compatibility.

Factors Affecting Performance:

- Sunlight availability
- Orientation
- Tilt angle
- Shading
- Dust and dirt
- Temperature
- Installation quality
- System losses
- Panel degradation

Solar Panel Degradation:

Solar panels gradually lose some power output over their operating life. The degradation rate depends on panel technology, manufacturer, environmental conditions, and product quality.

Panel Selection:

Selection should consider:

- Required system capacity
- Available installation area
- Energy consumption
- Panel efficiency
- Panel wattage
- Budget
- Warranty
- Manufacturer specifications
- Environmental conditions
- Compatibility with inverter and other components

Customer Questions:

Customers may ask about panel types, wattage, efficiency, number of panels required, lifespan, shading, performance, and panel selection.

Important Limitation:

Actual panel selection and system sizing should be verified by a qualified solar professional using electricity consumption, site conditions, installation area, equipment specifications, and applicable requirements.
""",

"inverters.txt": """
SOLAR INVERTERS

Definition:

A solar inverter is an electrical device that converts direct current (DC) electricity generated by solar panels or stored in batteries into alternating current (AC) electricity used by many electrical appliances and systems.

Main Functions:

- Convert DC electricity to AC electricity
- Manage solar power generation
- Monitor system performance
- Provide protection functions
- Coordinate with batteries and the grid when supported

Common Types:

1. On-grid inverter
2. Off-grid inverter
3. Hybrid inverter
4. Microinverter

On-Grid Inverter:

An on-grid inverter is designed to operate with a utility electricity grid.

Characteristics:

- Converts solar DC into AC
- Works with grid-connected solar systems
- Usually does not require batteries
- Can support export of excess electricity where permitted

Off-Grid Inverter:

An off-grid inverter is designed for systems that operate independently of the utility grid.

Characteristics:

- Works with battery storage
- Supplies AC electricity to loads
- Manages energy from solar panels and batteries
- Suitable for systems without reliable grid access

Hybrid Inverter:

A hybrid inverter can coordinate solar generation, battery storage, loads, and grid electricity depending on its design.

Potential Functions:

- Solar energy conversion
- Battery charging
- Battery discharging
- Grid interaction
- Backup power
- Energy management

Microinverters:

Microinverters are installed at or near individual solar panels and convert DC to AC at the panel level.

They can be useful in systems with shading or complex roof layouts, depending on the design.

Important Specifications:

- Rated power
- Maximum PV input power
- Maximum DC voltage
- MPPT voltage range
- Maximum input current
- AC output voltage
- Efficiency
- Number of MPPTs
- Battery compatibility
- Communication features
- Protection features
- Warranty

Inverter Sizing:

The inverter should be appropriately matched with the solar array and electrical loads.

Inverter selection depends on:

- Solar panel capacity
- Maximum load
- Daily energy consumption
- Battery requirements
- System type
- Grid requirements
- Future expansion
- Manufacturer specifications

Important:

A larger inverter is not automatically better. The inverter must be compatible with the panels, batteries, loads, and electrical system.

Customer Questions:

Customers may ask about inverter types, inverter capacity, hybrid inverters, battery compatibility, backup capability, efficiency, brands, and inverter sizing.

Important Limitation:

Final inverter selection should be confirmed by a qualified solar professional using the complete system design and equipment specifications.
""",

"batteries.txt": """
SOLAR BATTERIES

Definition:

A solar battery stores electrical energy so that it can be used when solar generation is unavailable or when backup power is required.

Main Uses:

- Energy storage
- Backup power
- Night-time energy use
- Supporting off-grid and hybrid systems
- Reducing dependence on the grid where applicable

Common Battery Types:

1. Lead-acid batteries
2. Lithium-ion batteries

Lead-Acid:

Lead-acid batteries are a traditional energy-storage technology. They can have a lower initial cost but generally require more maintenance and have different depth-of-discharge characteristics than lithium batteries.

Lithium-Ion:

Lithium-ion batteries are widely used in modern energy-storage systems. They generally offer high energy density, longer cycle life, and lower maintenance requirements compared with traditional lead-acid batteries.

Important Specifications:

- Battery capacity
- Voltage
- Usable energy
- Depth of discharge
- Cycle life
- Charging requirements
- Compatibility with inverter

Battery Selection:

Selection depends on:

- Required backup time
- Electrical loads
- Energy consumption
- System type
- Budget
- Available space
- Inverter compatibility

Backup Calculation:

Required battery capacity depends on the power of the loads that need backup and the required backup duration.

Customer Questions:

Customers may ask about battery types, capacity, backup time, battery life, compatibility, installation, maintenance, and warranty.

Important Limitation:

Actual battery sizing and selection should be verified by a qualified solar professional using the complete electrical load and system design.
""",

"systems.txt": """
SOLAR SYSTEM TYPES

Solar systems can generally be classified into three main types:

1. ON-GRID SYSTEM
2. OFF-GRID SYSTEM
3. HYBRID SYSTEM

ON-GRID SYSTEM:

An on-grid solar system is connected to the utility electricity grid.

Characteristics:

- Solar panels generate electricity during suitable sunlight conditions.
- The system works with the utility grid.
- Battery storage is not necessarily required.
- Excess generation may be handled according to applicable grid arrangements and regulations.

Advantages:

- Suitable for locations with reliable grid access
- Can reduce electricity purchased from the grid
- Usually simpler than systems with battery storage

Limitations:

- Grid-connected systems generally depend on grid availability for normal operation.
- Backup capability depends on the specific system design.

OFF-GRID SYSTEM:

An off-grid solar system operates independently of the utility grid.

Characteristics:

- Solar panels provide electricity.
- Batteries store energy when solar generation is insufficient.
- An inverter manages conversion and supply.

Advantages:

- Useful where grid access is unavailable or unreliable
- Can provide energy independence when properly designed

Limitations:

- Requires appropriate battery storage
- Generation and storage must be correctly sized

HYBRID SYSTEM:

A hybrid solar system combines solar generation, battery storage, and grid interaction depending on the design.

Characteristics:

- Solar panels generate electricity.
- Batteries can store energy.
- Grid power can be used when required.
- Backup can be available for selected loads depending on configuration.

Advantages:

- Greater flexibility
- Backup capability
- Combines solar, battery, and grid electricity

Limitations:

- More components and control requirements
- Usually greater complexity and cost

SYSTEM SELECTION:

The appropriate system depends on:

- Grid availability
- Electricity consumption
- Backup requirements
- Battery requirements
- Budget
- Major electrical loads
- Available installation area

Customer Questions:

Customers may ask about on-grid, off-grid, and hybrid systems, suitability, backup capability, batteries, and system costs.

Important Limitation:

Final system selection should be confirmed by a qualified solar professional after evaluating the site, electrical loads, grid conditions, and applicable requirements.
""",

"energy_consumption.txt": """
SOLAR ENERGY CONSUMPTION

Definition:

Energy consumption is the amount of electrical energy used by appliances and electrical equipment over a period of time.

The common unit for electricity consumption is kilowatt-hour (kWh).

Basic Formula:

Energy Consumption (Wh) = Power (W) × Operating Time (hours)

For kilowatt-hours:

Energy Consumption (kWh) = Power (kW) × Operating Time (hours)

Example:

A 1000 W appliance operating for 2 hours consumes approximately:

1000 × 2 = 2000 Wh

or

2 kWh

Daily Energy Consumption:

Daily consumption can be estimated by calculating the energy used by each appliance and adding the results.

Example:

Fan:
100 W × 8 hours = 800 Wh

Refrigerator:
150 W × 10 hours equivalent = 1500 Wh

Lights:
20 W × 5 hours = 100 Wh

Total estimated consumption:

2400 Wh = 2.4 kWh per day

Important Loads:

Solar system planning may consider:

- Lights
- Fans
- Refrigerators
- TVs
- Computers
- Washing machines
- Water pumps
- Air conditioners
- Motors
- Kitchen appliances
- Other electrical equipment

Load Information:

For each appliance, collect:

- Appliance name
- Rated power
- Quantity
- Hours of operation per day
- Starting or surge requirements where applicable

Peak Load:

Peak load is the highest electrical demand occurring when multiple appliances operate simultaneously.

Peak load is important when selecting an inverter.

Energy Consumption and Solar Sizing:

Daily energy consumption is one of the important inputs used to estimate the required solar generation capacity.

Actual generation depends on:

- Solar irradiation
- Location
- Panel orientation
- Panel tilt
- Shading
- Temperature
- System losses
- Equipment efficiency

Customer Questions:

Customers may ask how to calculate electricity consumption, how many units they use, what appliances consume the most electricity, and how consumption affects solar sizing.

Important Limitation:

Energy consumption estimates should be based on actual electricity bills, appliance ratings, measured usage, or professional load assessment where possible.
""",

"sizing.txt": """
SOLAR SYSTEM SIZING

Definition:

Solar system sizing is the process of estimating the required solar panel capacity, inverter capacity, battery capacity, and related components based on energy consumption, electrical loads, site conditions, and system requirements.

Important Inputs:

- Daily energy consumption
- Peak load
- Appliance load
- Required backup duration
- Available installation area
- Solar resource
- Grid availability
- System type
- Budget
- Future expansion requirements

Basic Solar Capacity Concept:

Approximate solar capacity can be estimated using:

Required Solar Capacity ≈ Daily Energy Consumption ÷ Peak Sun Hours

A practical design should also account for system losses and other site-specific factors.

Example:

If daily consumption is 10 kWh and effective peak sun hours are approximately 5 hours:

10 ÷ 5 = 2 kW

This is only a basic conceptual estimate and is not a final system design.

Panel Count:

Approximate panel count can be estimated using:

Number of Panels = Required Solar Capacity ÷ Panel Power

Example:

A 2 kW system using 500 W panels:

2000 ÷ 500 = 4 panels

Actual panel count should be adjusted according to system design and available products.

Inverter Sizing:

Inverter sizing should consider:

- Maximum simultaneous load
- Solar array capacity
- Surge requirements
- System type
- Battery compatibility
- Manufacturer specifications

Battery Sizing:

Battery sizing depends on:

- Backup load
- Required backup duration
- Battery voltage
- Usable battery capacity
- Depth of discharge
- System efficiency

Basic Concept:

Battery Energy Required ≈ Backup Load × Backup Time

Actual battery capacity should include efficiency and allowable depth-of-discharge considerations.

Load Assessment:

A proper load assessment should identify:

- Essential loads
- Non-essential loads
- Peak loads
- Continuous loads
- Starting or surge loads

System Type:

Sizing differs between:

- On-grid systems
- Off-grid systems
- Hybrid systems

Customer Questions:

Customers may ask:

- How many panels do I need?
- What size inverter do I need?
- What battery size do I need?
- What solar system is suitable for my house?
- How many kW are required?

Important Limitation:

The formulas in this document are basic estimation concepts. Final system sizing must be performed or verified by a qualified solar professional using actual load data, site conditions, solar resource, equipment specifications, applicable electrical requirements, and safety considerations.
""",

"pricing.txt": """
SOLAR SYSTEM PRICING

Definition:

Solar system pricing refers to the total cost of equipment, installation, electrical work, protection devices, structure, transportation, and other services required to install a solar energy system.

Major Cost Components:

- Solar panels
- Inverter
- Batteries where required
- Mounting structure
- DC cables
- AC cables
- Protection devices
- Electrical distribution equipment
- Installation labor
- Transportation
- Monitoring equipment
- Maintenance or service arrangements

Factors Affecting Price:

- System capacity
- Panel type and brand
- Inverter type and brand
- Battery capacity
- Battery technology
- Installation complexity
- Roof structure
- Cable length
- Protection requirements
- Location
- Labor costs
- Warranty
- Market conditions

On-Grid Pricing:

On-grid systems may have lower initial costs than systems requiring significant battery storage because batteries are not necessarily included.

Off-Grid Pricing:

Off-grid systems generally require battery storage and may therefore have higher equipment costs.

Hybrid Pricing:

Hybrid systems can have higher costs because they may include solar panels, batteries, hybrid inverters, protection equipment, and additional control functionality.

Price Quotes:

A professional quotation should clearly identify:

- System capacity
- Equipment specifications
- Quantity
- Installation scope
- Warranty
- Included accessories
- Payment terms
- Expected timeline
- Any exclusions

Important:

Solar prices can change based on location, supplier, equipment availability, exchange rates, taxes, market conditions, and installation requirements.

Customer Questions:

Customers may ask about solar system costs, panel prices, inverter prices, battery prices, installation costs, and complete system quotations.

Important Limitation:

The chatbot should not provide a final or guaranteed price without current supplier data and a site-specific quotation.
""",

"installation.txt": """
SOLAR INSTALLATION

Definition:

Solar installation is the process of installing and connecting solar panels, inverters, batteries, mounting structures, electrical protection equipment, and related components.

Typical Installation Steps:

1. Site assessment
2. Electricity consumption assessment
3. System design
4. Equipment selection
5. Structural assessment
6. Mounting structure installation
7. Solar panel installation
8. DC wiring
9. Inverter installation
10. Battery installation where applicable
11. AC wiring
12. Protection equipment installation
13. System configuration
14. Testing and commissioning
15. Customer handover

Site Assessment:

A site assessment may consider:

- Roof condition
- Roof orientation
- Roof tilt
- Shading
- Available installation area
- Structural strength
- Cable routing
- Electrical connection
- Access and safety

Panel Installation:

Panels should be installed securely using suitable mounting structures and appropriate spacing.

Inverter Installation:

The inverter should be installed according to manufacturer requirements, environmental conditions, ventilation requirements, and electrical safety standards.

Battery Installation:

Battery installation must follow manufacturer requirements for location, temperature, ventilation where applicable, electrical protection, and safe handling.

Safety:

Solar installation involves electrical and working-at-height risks.

Important safety considerations include:

- Proper electrical isolation
- Appropriate protective equipment
- Correct cable sizing
- Correct polarity
- Grounding and protection
- Suitable mounting
- Safe working practices
- Compliance with applicable electrical requirements

Testing:

Before commissioning, the system should be checked for:

- Correct wiring
- Voltage
- Polarity
- Protection devices
- Communication
- Inverter configuration
- Battery configuration where applicable
- System operation

Customer Questions:

Customers may ask about installation time, roof requirements, installation steps, wiring, safety, maintenance, and commissioning.

Important Limitation:

Solar installation should be performed by qualified professionals following manufacturer instructions and applicable electrical and safety requirements.
""",

"maintenance.txt": """
SOLAR SYSTEM MAINTENANCE

Definition:

Solar maintenance involves inspecting and servicing the solar system to help maintain safe and reliable operation.

Common Maintenance Tasks:

- Panel inspection
- Panel cleaning when necessary
- Cable inspection
- Mounting structure inspection
- Inverter inspection
- Battery inspection where applicable
- Electrical protection inspection
- Performance monitoring

Solar Panel Cleaning:

Dust, dirt, bird droppings, and other contamination can reduce solar panel output.

Cleaning frequency depends on:

- Local environment
- Dust levels
- Rainfall
- Panel angle
- Nearby pollution
- Bird activity

Inverter Maintenance:

Check for:

- Error messages
- Abnormal noise
- Overheating
- Ventilation problems
- Communication issues
- Unexpected shutdowns

Battery Maintenance:

Battery maintenance depends on battery technology.

Lead-acid batteries may require more maintenance than many modern lithium-ion systems.

Performance Monitoring:

System performance can be monitored through:

- Inverter displays
- Mobile applications
- Web monitoring platforms
- Energy meters

Warning Signs:

- Significant reduction in energy generation
- Repeated inverter errors
- Battery alarms
- Damaged cables
- Loose mounting
- Physical panel damage
- Unusual electrical behavior

Customer Questions:

Customers may ask how often panels should be cleaned, how to maintain batteries, how to check inverter performance, and what to do when solar production decreases.

Important Limitation:

Electrical repairs and potentially hazardous maintenance should be performed by qualified professionals.
""",

"warranty.txt": """
SOLAR WARRANTY

Definition:

A solar warranty is a manufacturer's or installer's commitment covering specified products or services for a defined period under stated terms and conditions.

Common Warranty Categories:

1. Product warranty
2. Performance warranty
3. Inverter warranty
4. Battery warranty
5. Installation workmanship warranty

Panel Product Warranty:

Covers specified manufacturing or material defects according to manufacturer terms.

Panel Performance Warranty:

May specify minimum expected power output over a defined period.

Inverter Warranty:

Covers specified inverter defects and failures according to manufacturer terms.

Battery Warranty:

Battery warranties may specify:

- Warranty duration
- Cycle limitations
- Throughput limitations
- Operating conditions
- Depth-of-discharge conditions
- Installation requirements

Installation Warranty:

An installer may provide a separate workmanship warranty covering installation-related issues.

Important Warranty Conditions:

Warranty coverage may depend on:

- Proper installation
- Correct operating conditions
- Product registration
- Maintenance requirements
- Authorized service procedures
- Environmental conditions
- Manufacturer terms

Customer Questions:

Customers may ask about warranty duration, panel warranty, inverter warranty, battery warranty, installation warranty, and warranty claims.

Important Limitation:

Warranty terms vary by manufacturer, product, installer, country, and supplier. The chatbot should not promise warranty coverage without checking the actual warranty documentation.
""",

"faq.txt": """
SOLAR FAQ

Q: What is solar energy?

A: Solar energy is energy obtained from sunlight and can be converted into electricity using photovoltaic solar panels.

Q: What is a solar panel?

A: A solar panel is a photovoltaic device that converts sunlight into electrical energy.

Q: What is a solar inverter?

A: A solar inverter converts DC electricity from solar panels or batteries into AC electricity used by many electrical appliances.

Q: What are the main types of solar systems?

A: The main types are on-grid, off-grid, and hybrid systems.

Q: What is an on-grid system?

A: An on-grid system is connected to the utility electricity grid.

Q: What is an off-grid system?

A: An off-grid system operates independently of the utility grid and normally requires battery storage.

Q: What is a hybrid system?

A: A hybrid system combines solar generation, battery storage, and grid interaction depending on the system design.

Q: Do solar panels work at night?

A: Solar panels require sunlight to generate electricity, so they do not normally generate useful electricity at night. Stored battery energy or grid electricity can be used instead.

Q: Do solar panels work on cloudy days?

A: Solar panels can generate electricity during cloudy conditions, but output is generally lower than under strong direct sunlight.

Q: How many solar panels do I need?

A: The required number depends on electricity consumption, solar resource, panel wattage, system losses, available area, and system design.

Q: Do I need batteries?

A: Batteries are generally important for off-grid systems and can provide backup or energy storage in hybrid systems. They are not necessarily required for basic on-grid systems.

Q: What is battery capacity?

A: Battery capacity represents the amount of electrical energy that a battery can store, commonly expressed in kWh.

Q: How long can a battery provide backup?

A: Backup duration depends on battery usable energy and the power consumed by the connected loads.

Q: Which solar panel is best?

A: The appropriate panel depends on efficiency, wattage, quality, warranty, available space, budget, and system requirements.

Q: Which is better, monocrystalline or polycrystalline?

A: Modern monocrystalline panels generally offer higher efficiency, while polycrystalline panels can provide a cost-effective option depending on the application.

Q: How long do solar panels last?

A: Solar panels are designed for long-term operation, but their output gradually decreases over time. Actual service life depends on product quality, environmental conditions, and maintenance.

Q: What affects solar panel output?

A: Sunlight, shading, temperature, orientation, tilt, dirt, installation quality, and system losses can affect output.

Q: How is solar system size estimated?

A: Basic estimation uses daily energy consumption, available solar resource, system losses, and equipment characteristics.

Q: Can solar provide backup during a power outage?

A: Backup depends on the system design. Standard grid-connected systems may shut down during grid outages, while appropriately designed hybrid or off-grid systems can provide backup.

Q: Why is my solar production lower than expected?

A: Possible causes include shading, dirt, high temperature, equipment problems, incorrect configuration, seasonal changes, or other system losses.

Q: Can I run an air conditioner on solar?

A: Yes, but the solar system must be appropriately sized for the air conditioner's running power, starting requirements, operating hours, and other loads.

Q: Can solar reduce my electricity bill?

A: A properly designed solar system can reduce electricity purchased from the grid, but savings depend on energy consumption, system size, solar generation, electricity tariffs, and applicable policies.

Important Limitation:

The chatbot should provide general information and basic estimates. Final equipment selection, system sizing, electrical design, installation, pricing, and safety decisions should be verified by qualified solar professionals.
"""
}

for filename, content in files.items():
    path = BASE / filename
    path.write_text(content.strip() + "\n", encoding="utf-8")
    print(f"Created: {path} ({path.stat().st_size} bytes)")

print("\nKnowledge base population complete.")